version: "3.8"

volumes:
  article-db_data:

networks:
  article:

services:
  db:
    image: postgres:15.1-alpine
    container_name: article-db
    restart: "always"
    ports:
      - '$DB_LOCAL_PORT:$DB_DOCKER_PORT'
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    volumes:
      - article-db_data:/var/lib/postgres
    networks:
      - article

  app:
    depends_on:
      - db
    container_name: article-core
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .m2:/root/.m2
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://db:$DB_DOCKER_PORT/$DB_DATABASE",
        "spring.datasource.username" : "$DB_USER",
        "spring.datasource.password" : "$DB_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "none"
      }'
    env_file: .env
    ports:
      - '$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT'
    stdin_open: true
    tty: true
    networks:
      - article
