spring:
  datasource:
    url: jdbc:postgresql://localhost:5491/article
    username: article
    password: article
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  jwt:
    secret:
      access: MzA0NjAyMjEwMGU2NDU1NDY1NDRlNGVhZmUzZjNkNDcwNzM5NDU5MmM4YTY0N2ZkYWU0NzViNjJiOGU0NDIzZWU5ZTU0NDgzZjgwMjIxMDBjNDJiMTc0YTI3NTU1ZmNiZGM3YTExY2MyOTc0ZWQzZWZhZjljODc4NGY2ZDFhNTZjZjc4MTI2MzcwMWMxNWIz
logging:
  file:
    path: /Users/ivanalekseev/Documents/log/
