version: "3.8"

volumes:
  article-db_data:

networks:
  article:

services:
  db:
    image: postgres:15.1-alpine
    restart: "always"
    ports:
      - '$DB_LOCAL_PORT:$DB_DOCKER_PORT'
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    volumes:
      - article-db_data:/var/lib/postgres
    networks:
      - article